version: '3'
services:
  mongo_db:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db

  express_app:
    build: 
      context: ./server/database
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
    depends_on:
      - mongo_db
    environment:
      - MONGODB_URI=mongodb://mongo_db:27017/dealershipsDB
    volumes:
      - ./server/database:/app
      - /app/node_modules

volumes:
  mongodb_data: 