services:
  mongo_db:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db

  express_app:
    build: 
      context: ./server/database
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
    depends_on:
      - mongo_db
    environment:
      - MONGODB_URI=mongodb://mongo_db:27017/dealershipsDB
    volumes:
      - ./server/database:/app
      - /app/node_modules

  django_app:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
    depends_on:
      - mongo_db
      - express_app

  react_app:
    build:
      context: ./server/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./server/frontend:/app
      - /app/node_modules
    depends_on:
      - django_app

volumes:
  mongodb_data: 