services:
  # Mongodb service
  mongo_db:
    image: mongo:latest
    ports:
      - "27019:27017"
    volumes:
      - mongodb_data:/data/db

  # Node api service
  express_app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
    depends_on:
      - mongo_db
    environment:
      - MONGODB_URI=mongodb://mongo_db:27017/dealershipsDB
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  mongodb_data: {}
