apiVersion: apps/v1
kind: Deployment
metadata:
  name: dealership
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dealership
  template:
    metadata:
      labels:
        app: dealership
    spec:
      containers:
      - name: dealership
        image: us.icr.io/sn-labs-bonillamigue/dealership:v1
        ports:
        - containerPort: 8000