name: Python Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pylint black isort
        pip install -r server/requirements.txt
    
    - name: Run Black
      run: |
        black --check server/
      continue-on-error: true
    
    - name: Run isort
      run: |
        isort --check-only --diff server/
      continue-on-error: true
    
    - name: Run Flake8
      run: |
        flake8 server/ --max-line-length=120 --extend-ignore=E203
      continue-on-error: true
    
    - name: Run Pylint
      run: |
        pylint server/ --disable=C0111,C0103,C0303,C0301,W0611,R0903,E1101
      continue-on-error: true

    - name: HTML Lint
      run: |
        pip install html5lib
        find server/frontend/static -name "*.html" -exec python -m html5lib {} \;
      continue-on-error: true
